use serde_json::Value;
use std::{fs,path::Path,time::{Duration,Instant},collections::BTreeMap};
use turnloop_mongodb::{bson::doc,topology::{Topology,TopologyType,ServerType},uri::{Options,ReadPreference}};
fn kind(s:&str)->ServerType{match s{"RSPrimary"=>ServerType::RSPrimary,"RSSecondary"=>ServerType::RSSecondary,"RSArbiter"=>ServerType::RSArbiter,"RSOther"=>ServerType::RSOther,"RSGhost"=>ServerType::RSGhost,"PossiblePrimary"=>ServerType::PossiblePrimary,"Mongos"=>ServerType::Mongos,"Standalone"=>ServerType::Standalone,"Unknown"=>ServerType::Unknown,_=>panic!("Unexpected server type {s}")}}
fn files(root:&Path,out:&mut Vec<std::path::PathBuf>){for e in fs::read_dir(root).unwrap(){let p=e.unwrap().path();if p.is_dir(){files(&p,out)}else if p.extension().is_some_and(|e|e=="json"){out.push(p)}}}
fn run(path:&Path){let v:Value=serde_json::from_slice(&fs::read(path).unwrap()).unwrap();let now=Instant::now();let opts=Options::parse("mongodb://a/?directConnection=true").unwrap();let mut t=Topology::new(&opts,now);t.servers.clear();for s in v["topology_description"]["servers"].as_array().unwrap(){let a=s["address"].as_str().unwrap();let o=Options::parse(&format!("mongodb://{a}/?directConnection=true")).unwrap();let mut single=Topology::new(&o,now);single.update(a,&doc!{"ok":1,"maxWireVersion":27},now,Duration::from_secs_f64(s["avg_rtt_ms"].as_f64().unwrap_or(0.0)/1000.0));let mut server=single.servers.remove(a).unwrap();server.kind=kind(s["type"].as_str().unwrap());server.rtt=s["avg_rtt_ms"].as_f64().map(|n|Duration::from_secs_f64(n/1000.0));if let Some(tags)=s["tags"].as_object(){server.tags=tags.iter().map(|(k,v)|(k.clone(),v.as_str().unwrap().to_owned())).collect();}t.servers.insert(a.into(),server);}
 t.kind=match v["topology_description"]["type"].as_str().unwrap(){"Single"=>TopologyType::Single,"Unknown"=>TopologyType::Unknown,"Sharded"=>TopologyType::Sharded,"ReplicaSetNoPrimary"=>TopologyType::ReplicaSetNoPrimary,"ReplicaSetWithPrimary"=>TopologyType::ReplicaSetWithPrimary,x=>panic!("Unknown topology {x}")};
 let p=&v["read_preference"];let pref=if v["operation"]=="write"{ReadPreference::Primary}else{match p["mode"].as_str().unwrap(){"Primary"=>ReadPreference::Primary,"PrimaryPreferred"=>ReadPreference::PrimaryPreferred,"Secondary"=>ReadPreference::Secondary,"SecondaryPreferred"=>ReadPreference::SecondaryPreferred,"Nearest"=>ReadPreference::Nearest,x=>panic!("Mode {x}")}};
 let tags:Vec<BTreeMap<String,String>>=if v["operation"]=="write"{Vec::new()}else{p["tag_sets"].as_array().into_iter().flatten().map(|t|t.as_object().unwrap().iter().map(|(k,v)|(k.clone(),v.as_str().unwrap().into())).collect()).collect()};
 let mut actual=Vec::new();t.candidates(pref,&tags,None,&mut actual).unwrap();actual.sort();let mut expected:Vec<_>=v["in_latency_window"].as_array().unwrap().iter().map(|s|s["address"].as_str().unwrap()).collect();expected.sort();assert_eq!(actual,expected,"{}",path.display());
}
#[test]
fn official_server_selection(){let root=Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/spec/selection");let mut list=Vec::new();files(&root,&mut list);list.sort();assert!(!list.is_empty());let mut failures=Vec::new();for p in &list{if std::panic::catch_unwind(||run(p)).is_err(){failures.push(p.strip_prefix(&root).unwrap().display().to_string());}}eprintln!("Server selection: {} fixtures, {} failures",list.len(),failures.len());assert!(failures.is_empty(),"{}",failures.join("\n"));}
