//! sessions/driver-sessions.md §§ Server Session, Command Decoration;
//! transactions/transactions.md §§ State Machine, commitTransaction, abortTransaction;
//! change-streams/change-streams.md §§ Resume Process, Resume Tokens.
use crate::{wire::BsonWriter, Error, ErrorKind, Result};
use bson::{raw::RawDocument, Document, Timestamp};
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TransactionState {
    None,
    Starting,
    InProgress,
    Committed,
    Aborted,
}
#[derive(Debug)]
pub struct Session {
    pub id: [u8; 16],
    pub txn_number: i64,
    pub state: TransactionState,
    pub dirty: bool,
    pub operation_time: Option<Timestamp>,
    pub cluster_time: Option<Document>,
    pub pinned_server: Option<String>,
}
impl Session {
    /// Supply an RFC4122 UUID generated by the host. No entropy or clock reads here.
    pub fn new(id: [u8; 16]) -> Self {
        Self {
            id,
            txn_number: 0,
            state: TransactionState::None,
            dirty: false,
            operation_time: None,
            cluster_time: None,
            pinned_server: None,
        }
    }
    pub fn start_transaction(&mut self) -> Result<()> {
        if matches!(
            self.state,
            TransactionState::Starting | TransactionState::InProgress
        ) {
            return Err(Error::new(
                ErrorKind::InvalidArgument,
                "Transaction already in progress",
            ));
        }
        self.txn_number = self
            .txn_number
            .checked_add(1)
            .ok_or_else(|| Error::protocol("Transaction number exhausted"))?;
        self.state = TransactionState::Starting;
        self.pinned_server = None;
        Ok(())
    }
    pub fn next_retryable_write(&mut self) -> Result<()> {
        if matches!(
            self.state,
            TransactionState::Starting | TransactionState::InProgress
        ) {
            return Err(Error::new(
                ErrorKind::InvalidArgument,
                "Retryable write is inside a transaction",
            ));
        }
        self.txn_number = self
            .txn_number
            .checked_add(1)
            .ok_or_else(|| Error::protocol("Transaction number exhausted"))?;
        Ok(())
    }
    /// Decorates a retained writer before finish. Same txnNumber on a retry.
    pub fn decorate(&mut self, w: &mut BsonWriter, retryable_write: bool) -> Result<()> {
        let l = w.start_document("lsid", false)?;
        w.binary("id", 4, &self.id)?;
        w.end_document(l)?;
        if retryable_write
            || matches!(
                self.state,
                TransactionState::Starting | TransactionState::InProgress
            )
        {
            w.int64("txnNumber", self.txn_number)?;
        }
        if matches!(
            self.state,
            TransactionState::Starting | TransactionState::InProgress
        ) {
            w.boolean("autocommit", false)?;
            if self.state == TransactionState::Starting {
                w.boolean("startTransaction", true)?;
                self.state = TransactionState::InProgress;
            }
        }
        Ok(())
    }
    /// Returns false for an empty transaction, which completes locally.
    pub fn commit(&mut self, w: &mut BsonWriter, retry: bool) -> Result<bool> {
        if self.state == TransactionState::Starting {
            self.state = TransactionState::Committed;
            return Ok(false);
        }
        if !matches!(
            self.state,
            TransactionState::InProgress | TransactionState::Committed
        ) {
            return Err(Error::new(
                ErrorKind::InvalidArgument,
                "No transaction to commit",
            ));
        }
        self.end_command(w, "commitTransaction", retry)?;
        self.state = TransactionState::Committed;
        Ok(true)
    }
    pub fn abort(&mut self, w: &mut BsonWriter) -> Result<bool> {
        if self.state == TransactionState::Starting {
            self.state = TransactionState::Aborted;
            return Ok(false);
        }
        if self.state != TransactionState::InProgress {
            return Err(Error::new(
                ErrorKind::InvalidArgument,
                "No transaction to abort",
            ));
        }
        self.end_command(w, "abortTransaction", false)?;
        self.state = TransactionState::Aborted;
        Ok(true)
    }
    fn end_command(&self, w: &mut BsonWriter, name: &str, majority: bool) -> Result<()> {
        w.clear();
        w.int32(name, 1)?;
        let l = w.start_document("lsid", false)?;
        w.binary("id", 4, &self.id)?;
        w.end_document(l)?;
        w.int64("txnNumber", self.txn_number)?;
        w.boolean("autocommit", false)?;
        if majority {
            let c = w.start_document("writeConcern", false)?;
            w.string("w", "majority")?;
            w.int32("wtimeout", 10000)?;
            w.end_document(c)?;
        }
        w.string("$db", "admin")?;
        w.finish()?;
        Ok(())
    }
    pub fn observe(&mut self, reply: &Document) {
        if let Ok(t) = reply.get_timestamp("operationTime") {
            self.operation_time = Some(self.operation_time.map_or(t, |old| old.max(t)));
        }
        if let Ok(c) = reply.get_document("$clusterTime") {
            if let Ok(t) = c.get_timestamp("clusterTime") {
                if self
                    .cluster_time
                    .as_ref()
                    .and_then(|d| d.get_timestamp("clusterTime").ok())
                    .is_none_or(|old| t > old)
                {
                    self.cluster_time = Some(c.clone());
                }
            }
        }
    }
    pub fn retry_commit(error: &Error) -> bool {
        matches!(error.kind, ErrorKind::Network | ErrorKind::Timeout)
            || error.has_label("RetryableWriteError")
            || error.has_label("UnknownTransactionCommitResult")
    }
}
#[derive(Default, Debug)]
pub struct ChangeStream {
    pub resume_token: Option<Document>,
    pub start_after: bool,
    pub received_document: bool,
    pub operation_time: Option<Timestamp>,
    pub resumed: bool,
}
impl ChangeStream {
    pub fn observe_document(&mut self, event: &RawDocument) -> Result<()> {
        let id = event.get_document("_id").map_err(|_| {
            Error::protocol("Cannot provide resume functionality when the resume token is missing")
        })?;
        self.resume_token = Some(
            id.try_into()
                .map_err(|_| Error::protocol("Invalid resume token"))?,
        );
        self.received_document = true;
        self.resumed = false;
        Ok(())
    }
    /// Call only after consuming every document in the batch, including an empty batch.
    pub fn finish_batch(&mut self, token: Option<&RawDocument>) -> Result<()> {
        if let Some(t) = token {
            self.resume_token = Some(
                t.try_into()
                    .map_err(|_| Error::protocol("Invalid post batch resume token"))?,
            );
        }
        Ok(())
    }
    pub fn stage(&self) -> Document {
        let mut options = Document::new();
        if let Some(t) = &self.resume_token {
            options.insert(
                if self.start_after && !self.received_document {
                    "startAfter"
                } else {
                    "resumeAfter"
                },
                t.clone(),
            );
        } else if let Some(t) = self.operation_time {
            options.insert("startAtOperationTime", t);
        }
        bson::doc! {"$changeStream":options}
    }
    pub fn should_resume(&mut self, error: &Error, wire_version: i32) -> bool {
        if self.resumed {
            return false;
        }
        let allowed = matches!(error.kind, ErrorKind::Network | ErrorKind::Timeout)
            || if wire_version >= 9 {
                error.has_label("ResumableChangeStreamError")
            } else {
                error.code.is_some_and(|c| {
                    matches!(
                        c,
                        6 | 7
                            | 43
                            | 63
                            | 89
                            | 91
                            | 150
                            | 189
                            | 234
                            | 262
                            | 9001
                            | 10107
                            | 11600
                            | 11602
                            | 13388
                            | 13435
                            | 13436
                    )
                })
            };
        if allowed {
            self.resumed = true;
        }
        allowed
    }
}
