[package]
name = "turnloop-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
http.workspace = true
url = "2"
httparse = "1"
flate2 = "1"
brotli = "8"
turnloop-tls = { path = "../turnloop-tls" }

[dev-dependencies]
rcgen.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
zstd = { version = "0.13", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
ruzstd = "0.8"
