[package]
name = "turnloop-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Pull-driven sans-I/O PostgreSQL client protocol"

[dependencies]
bytes.workspace = true
postgres-protocol.workspace = true

[dev-dependencies]
rustls.workspace = true


[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
postgres-protocol = { workspace = true, features = ["js"] }
